server:
  port: 8080

#logging:
#  level:
#    org.springframework: DEBUG
#    org.hibernate: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format-sql: true
#    show-sql: true
  main:
    web-application-type: servlet